import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const PORT = Number(process.env.PORT || 3000);
const DURATION = Number(process.env.MATCH_SECONDS || 600) * 1000;
const rooms = new Map();
const root = path.resolve('public');
const resources = ['wood', 'stone', 'crystal'];
const buildings = ['core', 'grove', 'quarry', 'vault', 'workshop'];
const costs = [null, {wood:4,stone:3,crystal:0}, {wood:6,stone:5,crystal:1}, {wood:8,stone:7,crystal:3}];
const colors = ['#efbd68','#7dd0bd','#ea8f83','#a7a0df','#e5cf83','#82b3ed','#d89dd1','#a6cd87'];
const code = () => crypto.randomBytes(4).toString('hex').slice(0,5).toUpperCase();
const id = () => crypto.randomBytes(18).toString('base64url');
const score = p => buildings.reduce((n,b) => n + (b === 'core' ? [0,2,5,9][p.levels[b]] : [0,1,3,6][p.levels[b]]), 0) + (p.hall ? 4 : 0);
const complete = p => p.hall && buildings.every(b => p.levels[b] === 3);
const rank = (a,b) => score(b)-score(a) || b.stock.crystal-a.stock.crystal || resources.reduce((n,k)=>n+b.stock[k]-a.stock[k],0);
const publicPlayer = (p, now) => ({id:p.id,name:p.name,color:p.color,stock:p.stock,levels:p.levels,hall:p.hall,score:score(p),crew:p.crew.map(m=>m&&({...m,remaining:Math.max(0,m.ends-now)}))});
function state(room) { const now=Date.now(); return {code:room.code,phase:room.phase,host:room.host,players:room.players.map(p=>publicPlayer(p,now)),duration:DURATION,countdownRemaining:room.phase==='countdown'?Math.max(0,room.starts-now):0,remaining:room.phase==='playing'?Math.max(0,room.ends-now):room.phase==='finished'?0:DURATION,reason:room.reason,winners:room.winners,log:room.log.slice(-8)}; }
function send(room) { const payload=`data: ${JSON.stringify(state(room))}\n\n`; for(const response of room.clients) { try {response.write(payload);} catch {room.clients.delete(response);} } }
function log(room,msg) { room.log.push(msg); if(room.log.length>20)room.log.shift(); }
function finish(room, reason, winner) { if(room.phase!=='playing')return; room.phase='finished'; room.reason=reason; if(winner)room.winners=[winner.id]; else {const sorted=[...room.players].sort(rank); const first=sorted[0]; room.winners=sorted.filter(p=>rank(p,first)===0).map(p=>p.id);} log(room,room.winners.map(i=>room.players.find(p=>p.id===i)?.name).join(' & ')+' wins!'); send(room); }
function tick() { const now=Date.now(); for(const room of rooms.values()) { if(room.phase==='countdown'){if(now>=room.starts){room.phase='playing';room.ends=room.starts+DURATION;for(const p of room.players)p.nextPassive=room.starts+20000;log(room,'The match has begun!')}else{send(room);continue}}if(room.phase!=='playing')continue; for(const p of room.players) { while(p.nextPassive<=now) { p.stock.wood+=p.levels.grove; p.stock.stone+=p.levels.quarry; p.nextPassive+=20000; } for(let i=0;i<p.crew.length;i++){const m=p.crew[i]; if(!m||m.ends>now)continue; p.crew[i]=null; if(m.kind==='gather'){ const amount=m.resource==='crystal'?1:3; p.stock[m.resource]+=amount; log(room,`${p.name} gathered ${amount} ${m.resource}.`); } else { const target=room.players.find(x=>x.id===m.target); if(target){ const cap=[3,2,1,1][target.levels.vault]; const n=Math.min(cap,target.stock[m.resource]); target.stock[m.resource]-=n;p.stock[m.resource]+=n; log(room,`${p.name} raided ${target.name} for ${n} ${m.resource}.`); } } } } if(now>=room.ends)finish(room,'time'); else send(room); } }
setInterval(tick,500);
setInterval(()=>{for(const [k,r] of rooms)if(Date.now()-r.created>6*60*60*1000){for(const c of r.clients)c.end();rooms.delete(k)}},60000);
const json=(res,status,obj)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(obj));};
async function body(req) { let raw=''; for await(const chunk of req){raw+=chunk;if(raw.length>2048)throw Error('Request too large.');} try{return JSON.parse(raw||'{}')}catch{throw Error('Invalid request.')} }
function act(room,p,a) { const now=Date.now(); if(a.type==='start'){if(room.host!==p.id||room.phase!=='lobby'||room.players.length<2)throw Error('The host can start with 2–8 players.');room.phase='countdown';room.starts=now+5000;log(room,'The match begins in 5 seconds.');return;}
 if(room.phase!=='playing')throw Error('The match is not in progress.');
 if(a.type==='build'){const b=a.building;if(b==='hall'){if(p.hall)throw Error('Dispatch Hall already built.');const cost={wood:10,stone:9,crystal:5};for(const k of resources)if(p.stock[k]<cost[k])throw Error('Not enough resources.');for(const k of resources)p.stock[k]-=cost[k];p.hall=true;p.crew.push(null);log(room,`${p.name} built a Dispatch Hall!`);}else{if(!buildings.includes(b)||p.levels[b]>=3)throw Error('That building cannot be upgraded.');const next=p.levels[b]+1, cost=costs[next];for(const k of resources)if(p.stock[k]<cost[k])throw Error('Not enough resources.');for(const k of resources)p.stock[k]-=cost[k];p.levels[b]=next;log(room,`${p.name} upgraded ${b} to level ${next}.`);}if(complete(p))finish(room,'complete',p);return;}
 if(a.type==='dispatch'){const slot=p.crew.findIndex(x=>!x);if(slot<0)throw Error('All crews are busy.');if(!resources.includes(a.resource))throw Error('Choose a resource.');if(a.kind==='gather'){p.crew[slot]={kind:'gather',resource:a.resource,starts:now,ends:now+Math.max(2000,5000-p.levels.workshop*1000)};log(room,`${p.name} sent a cart for ${a.resource}.`);return;}
 if(a.kind==='raid'){const target=room.players.find(x=>x.id===a.target);if(!target||target===p)throw Error('Choose another player to raid.');if((p.cooldowns[target.id]||0)>now)throw Error('Wait before raiding this player again.');p.cooldowns[target.id]=now+20000;p.crew[slot]={kind:'raid',resource:a.resource,target:target.id,starts:now,ends:now+Math.max(5000,8000-p.levels.workshop*1000)};log(room,`${p.name} sent a raid toward ${target.name}.`);return;}}
 throw Error('Unknown action.'); }
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='POST'&&url.pathname==='/api/room'){const b=await body(req);const name=String(b.name||'').trim().slice(0,18);if(!name)throw Error('Enter a name.');let room;if(b.code){room=rooms.get(String(b.code).trim().toUpperCase());if(!room||room.phase!=='lobby')throw Error('That room is not open.');if(room.players.length>=8)throw Error('Room is full.');if(room.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))throw Error('That name is taken in this room.');}else{let c;do{c=code()}while(rooms.has(c));room={code:c,phase:'lobby',players:[],clients:new Set(),created:Date.now(),log:[],reason:null,winners:[]};rooms.set(c,room);}const player={id:id(),name,color:colors[room.players.length],stock:{wood:8,stone:7,crystal:0},levels:{core:0,grove:0,quarry:0,vault:0,workshop:0},hall:false,crew:[null],cooldowns:{},nextPassive:Infinity};room.players.push(player);room.host??=player.id;log(room,`${name} joined.`);send(room);return json(res,200,{code:room.code,token:player.id});}
 if(url.pathname==='/api/state'||url.pathname==='/api/events'||url.pathname==='/api/action'){const token=url.searchParams.get('token')||req.headers['x-player-token'];const room=[...rooms.values()].find(r=>r.players.some(p=>p.id===token));if(!room)return json(res,404,{error:'Session not found. Join a room again.'});const p=room.players.find(x=>x.id===token);
 if(url.pathname==='/api/state')return json(res,200,{...state(room),you:p.id});
 if(url.pathname==='/api/events'){res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache','connection':'keep-alive','access-control-allow-origin':'*'});room.clients.add(res);res.write(`data: ${JSON.stringify(state(room))}\n\n`);req.on('close',()=>room.clients.delete(res));return;}
 if(req.method!=='POST')return json(res,405,{error:'Method not allowed.'});act(room,p,await body(req));send(room);return json(res,200,{ok:true});}
 if(req.method!=='GET')return json(res,405,{error:'Method not allowed.'});let file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+path.sep))return json(res,403,{error:'Forbidden.'});const ext=path.extname(file);const types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png'};if(!fs.existsSync(file)||!types[ext])return json(res,404,{error:'Not found.'});res.writeHead(200,{'content-type':types[ext]+'; charset=utf-8'});fs.createReadStream(file).pipe(res);
 }catch(e){json(res,400,{error:e.message||'Request failed.'});}});
server.listen(PORT,'0.0.0.0',()=>console.log(`Ring Raid listening at http://localhost:${PORT}`));
